apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version
      version: v1
  template:
    metadata:
      labels:
        app: version
        version: v1
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=v1"
        ports:
        - containerPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version
      version: v2
  template:
    metadata:
      labels:
        app: version
        version: v2
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=v2"
        ports:
        - containerPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version
      version: v3
  template:
    metadata:
      labels:
        app: version
        version: v3
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=v3"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: version-service
spec:
  selector:
    app: version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678