apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
spec:
  selector:
    matchLabels:
      app: conco-api   # <--- allineato al Deployment
  jwtRules:
  - issuer: "https://dev-rzkchlfkzqyo3c07.us.auth0.com/"
    jwksUri: "https://dev-rzkchlfkzqyo3c07.us.auth0.com/.well-known/jwks.json"
    forwardOriginalToken: true
    outputPayloadToHeader: x-jwt-payload
    audiences: 
    - "http://conco-api"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
spec:
  selector:
    matchLabels:
      app: conco-api   # <--- già corretto
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
