apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: version-service
spec:
  host: version-service
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: version-routing
spec:
  hosts:
  - version-service
  http:
  - route:
    - destination:
        host: version-service
        subset: v1



