apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-demo-custom
spec:
  profile: demo
  components:
    pilot:
      k8s:
        replicaCount: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi